GET http://localhost:8080/api/v1/category
Accept: application/json

###

GET http://localhost:8080/api/v1/category/1
Accept: application/json

###

POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "name": "Turkish"
}

###

PUT http://localhost:8080/api/v1/category/1
Content-Type: application/json

{
  "name": "American"
}

###

DELETE http://localhost:8080/api/v1/category/16
Content-Type: application/json

###

POST http://localhost:8080/api/v1/initCategory
Content-Type: application/json
