GET http://localhost:8080/api/v1/restaurant
Accept: application/json

###

GET http://localhost:8080/api/v1/restaurantsByName/Mersin
Accept: application/json

###

GET http://localhost:8080/api/v1/restaurantsByCategory/Turkish
Accept: application/json

###

GET http://localhost:8080/api/v1/restaurant/1
Accept: application/json

###
POST http://localhost:8080/api/v1/restaurant
Content-Type: application/json

{
  "name": "Macdonalds",
  "category": "American",
  "averageCost": "12",
  "address": "Beirut",
  "phoneNumber": "03564819"
}

###

PUT http://localhost:8080/api/v1/restaurant/1
Content-Type: application/json

{
  "name": "Al Turki2",
  "category": "Turkish",
  "averageCost": "12",
  "address": "Nabatieh",
  "phoneNumber": "03564819"
}

###

DELETE http://localhost:8080/api/v1/restaurant/1
Content-Type: application/json

###