GET http://localhost:8080/api/v1/visit
Accept: application/json

###
GET http://localhost:8080/api/v1/visitsByPersonId/1
Accept: application/json

###

GET http://localhost:8080/api/v1/visit/1
Accept: application/json

###

POST http://localhost:8080/api/v1/visit/person/1/restaurant/1
Content-Type: application/json

{
  "date": "14-11-2020 10:0:0"
}

###

PUT http://localhost:8080/api/v1/visit/1/person/1/restaurant/2
Content-Type: application/json

{
  "date": "14-11-2020 5:0:0"
}

###

DELETE http://localhost:8080/api/v1/visit/107
Content-Type: application/json

###